const getPronoums = (gender) => {
    const mascPronoums = [
        'meu'    ]

    const femPronoums = [
        'minha'
    ]

    if (gender == 'masc') {
        return mascPronoums;
    } else {
        return femPronoums;
    }
};

const getPrefix = () =>  {
    const preffix = [
        'Fala',
        'Opa',
        'Oi'
    ];

    return preffix;
};

const getAdjectives = (gender) => {
    const mascAdjectives = [
        'Campeão',
        'Federal',
        'Batizado',
        'Aspirante',
        'Apóstolo',
        'Pontual',
        'Companheiro',
        'Balaústre',
        'Acionista',
        'Promotor',
        'Patrão',
        'Incorreto',
        'Peregrino',
        'Estrategista',
        'Tributarista',
        'Comediante',
        'Supra-sumo',
        'Maestro',
        'Influencer',
        'Desbravador',
        'Tupi-guarani',
        'Sensei',
        'Negacionista',
        'Isolado',
        'Verificado',
        'Nórdico',
        'Vigilante',
        'Dramaturgo',
        'Combatente',
        'Historiador',
        'Tupã',
        'Escrivão',
        'Pecador',
        'Jogador',
        'Abençoado',
        'Fera',
        'Bancarizado',
        'Bancário',
        'Engenheiro',
        'Paladino',
        'Misterioso',
        'Vanguardista',
        'Camponês',
        'Celibatário',
        'Afrontoso',
        'Palestrinha',
        'Jesuíta',
        'Gerente',
        'Antagonista',
        'Pragmático',
        'Extravagante',
        'Monarca',
        'Ébano',
        'Cheiroso',
        'Aristocrata',
        'Imaculado',
        'Orixá',
        'Eloquente',
        'Artilheiro',
        'Bibelô',
        'Almirante',
        'Consagrado',
        'Sambarilove',
        'Afortunado',
        'Sonhador',
        'Protagonista',
        'Enigmático',
        'Querubim',
        'Cosmonauta',
        'Travesso',
        'Resplandescente',
        'Avassalador',
        'Socrático',
        'Homologado',
        'Confinado',
        'Conspiracionista',
        'Arrojado',
        'Iônico',
        'Federado',
        'Indomável',
        'Predador',
        'Iluminista',
        'Iluminado',
        'Talentoso',
        'Bacharel',
        'Modernista',
        'Bolivariano',
        'Camisa 10'
    ];

    const femAdjectives = [
        'Campeã',
        'Federal',
        'Batizada',
        'Aspirante',
        'Apóstola',
        'Pontual',
        'Companheira',
        'Balaústre',
        'Acionista',
        'Promotora',
        'Patroa',
        'Incorreta',
        'Peregrina',
        'Estrategista',
        'Tributarista',
        'Comediante',
        'Supra-sumo',
        'Maestra',
        'Influencer',
        'Desbravadora',
        'Tupi-guarani',
        'Sensei',
        'Negacionista',
        'Isolada',
        'Verificada',
        'Nórdica',
        'Vigilante',
        'Dramaturga',
        'Combatente',
        'Historiadora',
        'Tupã',
        'Escrivã',
        'Pecadora',
        'Jogadora',
        'Abençoada',
        'Fera',
        'Bancarizada',
        'Bancária',
        'Engenheira',
        'Paladina',
        'Misteriosa',
        'Vanguardista',
        'Camponesa',
        'Celibatária',
        'Afrontosa',
        'Palestrinha',
        'Jesuíta',
        'Gerente',
        'Antagonista',
        'Pragmática',
        'Extravagante',
        'Monarca',
        'Ébano',
        'Cheirosa',
        'Aristocrata',
        'Imaculada',
        'Orixá',
        'Eloquente',
        'Artilheira',
        'Bibelô',
        'Almirante',
        'Consagrada',
        'Sambarilove',
        'Afortunada',
        'Sonhadora',
        'Protagonista',
        'Enigmática',
        'Querubim',
        'Cosmonauta',
        'Travessa',
        'Resplandescente',
        'Avassaladora',
        'Socrática',
        'Homologada',
        'Confinada',
        'Conspiracionista',
        'Arrojada',
        'Iônica',
        'Federada',
        'Indomável',
        'Predadora',
        'Iluminista',
        'Iluminada',
        'Talentosa',
        'Bacharel',
        'Modernista',
        'Bolivariana',
        'Camisa 10'
    ]

    if (gender == 'masc') {
        return mascAdjectives;
    } else {
        return femAdjectives;
    }
};

module.exports = {
    getPrefix,
    getPronoums,
    getAdjectives
}